# Site settings
title: P1cKi:t
email: kjh@p1ck.it
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://p1ck.it/" # the base hostname & protocol for your site

instagram_username: test
facebook_username: test

# Build settings
markdown: kramdown
